#!/bin/bash
## Parse kubeconfig generated by k3s for certs
## Returns JSON object with server certificate, client certificate and client key to stdout
## Usage: certs.sh /path/to/private/ssh/key <ip of active server node> /path/to/project/root/

TMP_DIR="${3}/output"
TMP_FILE="${TMP_DIR}/kubeconfig"

# Delete downloaded file on exit
trap "rm -f ${TMP_FILE} > /dev/null 2>&1" EXIT
# Create output folder
mkdir -p ${TMP_DIR}
# Download generated kubeconfig
/bin/scp -o StrictHostKeyChecking=no -i $1 root@$2:/etc/rancher/k3s/k3s.yaml ${TMP_FILE} >/dev/null 2>&1
# Parse generated certificates
SERVER_CERT=$(grep certificate-authority-data ${TMP_FILE} | cut -d ":" -f 2 | tr -d " ")
CLIENT_CERT=$(grep client-certificate-data ${TMP_FILE} | cut -d ":" -f 2 | tr -d " ")
CLIENT_KEY=$(grep client-key-data ${TMP_FILE} | cut -d ":" -f 2 | tr -d " ")
# Return JSON
OUTPUT="{\"server_cert\": \"$SERVER_CERT\", \"client_cert\": \"$CLIENT_CERT\", \"client_key\": \"$CLIENT_KEY\"}"
echo $OUTPUT